name: Node

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: yarn
    - run: yarn build
    - run: yarn lint
    - run: yarn e2e
    - uses: ridedott/merge-me-action@v2
      if: ${{ github.event.workflow_run.conclusion == 'success' }}        
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PRESET: DEPENDABOT_MINOR
